apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-test-service
  labels:
    service: ingress-test-service
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ingress-test-service
      role: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: ingress-test-service
        role: app
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: belazar13/tic-tak-toe:echo-service-3
          env:
            - name: PORT_WEB
              value: '7001'
          securityContext:
            privileged: false
