apiVersion: v1
kind: Service
metadata:
  name: lb-ingress-test-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  labels:
    service: event-ingress-test-service
    role: app
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    service: ingress-test-service
    role: app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
